### ISSUE TITLE
.then

### ISSUE THREAD

**Issue by imcodingideas** [manuel-ruiz-23/pokemonApiTest#2]
https://github.com/manuel-ruiz-23/pokemonApiTest/blob/master/src/components/PokemonInfo/usePokemon.js#L9

Well, if you think about it do we need `.then` anymore? That's kind of old syntax.

**Comment by manuel-ruiz-23** [comment]
we sure have moved away from the callback hell. 

added ES7 await on c0b96c23f1e38234489508fbe5e525b424cb4e82
